 import { Metadata } from "next";
 
 export const metadata: Metadata = {
   title: {
    absolute: "About"
   },
   description: "Generated by Next.js",
 };

function About() {
  return (
    <div>
      <h1>About</h1>
    </div>
  )
}

export default About
    